apiVersion: skaffold/v1beta13
kind: Config
build:
  artifacts:
  - image: sebinsua/skaffold-mate
deploy:
  kubectl:
    manifests:
    - k8s/k8s-pod.yaml
portForward:
- resourceType: pod
  resourceName: mate
  port: 3000 
  localPort: 3001
